# Tablice:

In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(b)
np.transpose(b)
print(b)
np.linspace(0, 2, 10)
np.arange(0, 100, 5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

# Liczby losowe:

In [2]:
a = np.random.normal(size=20)
a = np.round(a, 2)
print(a)

a = np.random.randint(1, 1000, 100)
print(a)

np.zeros([3, 2])
np.ones([3, 2])

np.random.randint(1, 100, size=[5, 5], dtype=np.int32)


[-1.08 -0.64  0.3   1.63  0.36 -0.84  0.37 -0.53  0.49  1.34  1.56 -0.18
 -0.64 -0.48  1.   -0.71 -0.65 -0.15  0.14  1.89]
[227 324 389 922  91 477 896 550 104 202 273  83 986 518 660 138 428 549
 991 283 586 135 683 575 222 401 654 427  51 983 349 194 875 858 470 132
 705 734 279 253 301  31 764 472 868 683 252 333 167 389 887 405 965 797
 374 894 259 101 217 150 975 852 542 939 465 222 148 880 318 451 377 268
 460 507 845  91 902 325 931 837 853 398 662 664 136 273 793 161 168 210
 479 524  79 219 650 718 546 608 464 308]


array([[85, 80, 95, 11, 95],
       [54, 79,  6,  5, 41],
       [52, 93, 17, 68, 17],
       [10, 35, 58, 81, 99],
       [30, 31, 37, 37, 92]], dtype=int32)

# Zadanie liczby losowe:

In [ ]:
# a)
a = np.random.uniform(0, 10, 10)
# b)
b = a.astype(int)
# c)
c = np.round(a).astype(int)
print(a)
print(b)
print(c)

[2.84728545 7.10172986 5.7542717  4.97082273 5.0651026  2.78528379
 4.39267949 4.35095825 5.66392488 8.22299665]
[2 7 5 4 5 2 4 4 5 8]
[3 7 6 5 5 3 4 4 6 8]


# Selekcja danych:

In [ ]:
b=np.array([[1,2,3,4,5], [6,7,8,9,10]],dtype=np.int32)
print(np.ndim(b))
print(np.size(b))
print(b[0,1], b[0,3])
print(b[0,:])
print(b[:,0])

matrix = np.random.randint(0, 101, size=(20,7))
print(matrix[:, :4])

2
10
2 4
[1 2 3 4 5]
[1 6]
[[58 53 53 19]
 [48 52 52 25]
 [87 55 36 83]
 [ 5 45 73 74]
 [65 81 18 97]
 [88 54 43 26]
 [52 87 70  8]
 [ 2 31 66 15]
 [17 13 34 49]
 [85 16 31 45]
 [85 21 77 15]
 [81 29 18 93]
 [ 9 77 84 13]
 [31 97 70 59]
 [50 56 14 94]
 [83 44 88 32]
 [30 80 85 37]
 [99 16 14 10]
 [76 22 21 19]
 [65 74 29  6]]


# Operacje matematyczne i logiczne:

In [23]:
a = np.random.randint(0, 11, size=(3, 3))
b = np.random.randint(0, 11, size=(3, 3))

c = a + b
print(c)

c = a * b
print(c)

c = a / b
print(c)

c = np.power(a, b)
print(c)

c = a >= 4
print(c)

c = np.logical_and(a >= 1, a <= 4)
print(c)

c = np.trace(a)
print(c)

[[11  6 11]
 [19  6  3]
 [ 9 10 10]]
[[30  9 24]
 [90  8  2]
 [14  9 16]]
[[0.83333333 1.         2.66666667]
 [1.11111111 0.5        0.5       ]
 [0.28571429 0.11111111 0.25      ]]
[[     15625         27        512]
 [1000000000         16          1]
 [       128          1        256]]
[[ True False  True]
 [ True False False]
 [False False False]]
[[False  True False]
 [False  True  True]
 [ True  True  True]]
9


# Dane statystyczne: 

In [ ]:
print(b)

c = np.sum(b)
print(c)

c = np.min(b)
print(c)

c = np.max(b)
print(c)

c = np.std(b)
print(c)

c = np.mean(b, axis=1) # wiersze
print(c)

c = np.mean(b, axis=0) # kolumny
print(c)

[[4 2 0]
 [4 2 5]
 [8 7 1]]
33
0
8
2.5385910352879693
[2.         3.66666667 5.33333333]
[5.33333333 3.66666667 2.        ]


# Rzutowanie wymiarów za pomocą shape lub resize:

In [ ]:
tab = np.arange(50)
print(tab)
matrix_reshape = tab.reshape(10, 5)
print(matrix_reshape)
matrix_resize = np.resize(tab, (10, 5))
print(matrix_resize)

tab.ravel()

tab1 = np.arange(5)
tab2 = np.arange(4)

result = tab1[:, np.newaxis] + tab2
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


# Sortowanie danych:

In [ ]:
a=np.random.randn(5,5)
print(a)
print(np.sort(a, axis=1)) # wiersze
print(np.sort(a, axis=0)) # kolumny

b=np.array([(1,'MZ','mazowieckie'),
(2,'ZP','zachodniopomorskie'),
(3,'ML','małopolskie')])

matrix = np.array(b).reshape(3, 3)
print(matrix)
print(matrix[np.argsort(matrix[:, 1])])

[[ 0.07161853 -0.09494228 -0.30829949 -0.77621007  0.91648071]
 [-0.84158007 -0.81921982 -1.24469818  0.79392507  0.70621166]
 [ 1.66517729 -0.96714535 -0.74554584 -2.36442425  2.00927763]
 [ 0.78835696  0.0135716   0.64834318 -0.05276638  0.62985501]
 [-0.74308266  0.59116078 -0.73445037 -2.06531858  0.92058714]]
[[-0.77621007 -0.30829949 -0.09494228  0.07161853  0.91648071]
 [-1.24469818 -0.84158007 -0.81921982  0.70621166  0.79392507]
 [-2.36442425 -0.96714535 -0.74554584  1.66517729  2.00927763]
 [-0.05276638  0.0135716   0.62985501  0.64834318  0.78835696]
 [-2.06531858 -0.74308266 -0.73445037  0.59116078  0.92058714]]
[[-0.84158007 -0.96714535 -1.24469818 -2.36442425  0.62985501]
 [-0.74308266 -0.81921982 -0.74554584 -2.06531858  0.70621166]
 [ 0.07161853 -0.09494228 -0.73445037 -0.77621007  0.91648071]
 [ 0.78835696  0.0135716  -0.30829949 -0.05276638  0.92058714]
 [ 1.66517729  0.59116078  0.64834318  0.79392507  2.00927763]]
[['1' 'MZ' 'mazowieckie']
 ['2' 'ZP' 'zachodniopomor

# Zadania podsumowujące:

#### Zad 1

In [33]:
macierz = np.random.randint(100, size=(10, 5))
print(macierz)

print("Suma głównej przekątnej:", np.trace(macierz))

print(np.diag(macierz))

[[51 39  6 45 97]
 [67 35 13 84 90]
 [95 15 25 17 49]
 [37 37 90 66 13]
 [ 5 27 41 95 59]
 [16 36 88 54 45]
 [24 67  7 69 77]
 [35 58 23 32 12]
 [91 67 46 27 91]
 [ 8 26 14 64 93]]
Suma głównej przekątnej: 236
[51 35 25 66 59]


#### Zad 2

In [43]:
tab1 = np.random.normal(size=(5, 1))
tab2 = np.random.normal(size=(1, 5))

print(tab1 @ tab2) # macierzowo
print(tab1 * tab2) # po indeksach

[[-0.4667438   0.12587709  0.74898497 -0.06677163  0.05526145]
 [-0.1428503   0.03852559  0.22923224 -0.02043594  0.01691317]
 [-1.01004307  0.27240059  1.62081871 -0.14449516  0.11958691]
 [ 0.13758082 -0.03710445 -0.2207763   0.01968209 -0.01628927]
 [ 0.63713685 -0.17183074 -1.02241514  0.09114779 -0.07543562]]
[[-0.4667438   0.12587709  0.74898497 -0.06677163  0.05526145]
 [-0.1428503   0.03852559  0.22923224 -0.02043594  0.01691317]
 [-1.01004307  0.27240059  1.62081871 -0.14449516  0.11958691]
 [ 0.13758082 -0.03710445 -0.2207763   0.01968209 -0.01628927]
 [ 0.63713685 -0.17183074 -1.02241514  0.09114779 -0.07543562]]


#### Zad 3

In [45]:
tab1 = np.random.randint(1, 101, size=25)
tab2 = np.random.randint(1, 101, size=25)
tab1 = tab1.reshape(5, 5)
tab2 = tab2.reshape(5, 5)

print(tab1+tab2)

[[108  51  65  96 150]
 [ 84 122 160 148 134]
 [ 79 127  75 169  13]
 [143 144  45 105   6]
 [ 89  79 154 113  95]]


#### Zad 4

In [67]:
tab1 = np.random.randint(0, 101, size=(4, 5))
tab2 = np.random.randint(0, 101, size=(5, 4))

print(tab1 + tab2.T)

[[ 66  13 142  49 135]
 [178  38  89 182  93]
 [118  86  54  62 120]
 [170  52  94 170 115]]


#### Zad 5

In [68]:
print(tab1[:, 2]*tab2.T[:,3])

[ 644 5824  198 3828]


#### Zad 6

In [65]:
tab1 = np.random.normal(size=(3, 3))
tab2 = np.random.uniform(size=(3, 3))

print("Macierz 1.: średnia =", np.average(tab1), "odchylenie =", np.std(tab1), "wariancja =", np.var(tab1))
print("Macierz 2.: średnia =", np.average(tab2), "odchylenie =", np.std(tab2), "wariancja =", np.var(tab2))

Macierz 1.: średnia = -0.2609436842913712 odchylenie = 0.4689646063453448 wariancja = 0.21992780200464424
Macierz 2.: średnia = 0.37546180106780597 odchylenie = 0.30287327798018043 wariancja = 0.09173222251445964


#### Zad 7

In [64]:
a = np.arange(9).reshape(3, 3)
b = np.arange(9, 18).reshape(3, 3)

print(a*b) # mnożenie po indeksach
print(np.dot(a, b)) # mnożenie macierzowe

[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


#### Zad 8

In [63]:
a = np.arange(50).reshape(5, 10)
print(a)
print(np.lib.stride_tricks.as_strided(a, shape=(3, 5), strides=a.strides))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]


#### Zad 9

In [4]:
a = np.arange(9).reshape(3, 3)
b = np.arange(9, 18).reshape(3, 3)

print(np.vstack((a, b))) # macierz pod macierzą
print(np.hstack((a, b))) # macierz obok macierzy

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]


#### Zad 10

In [3]:
from numpy.lib.stride_tricks import as_strided

a = np.arange(24).reshape(4, 6)

print(np.max(as_strided(a, shape=(2, 3), strides=a.strides)))
print(np.max(as_strided(a[0][3:6], shape=(2, 3), strides=a.strides)))
print(np.max(as_strided(a[2], shape=(2, 3), strides=a.strides)))
print(np.max(as_strided(a[2][3:6], shape=(2, 3), strides=a.strides)))

8
11
20
23
