# Selekcja zmiennych za pomocą przyrostu informacji

In [1]:
import numpy as np
import pandas as pd

from scipy import sparse

Zad 1

In [2]:
x = [8,8,3,2,2,3,2,1,3,4,5,6,2,3,1,2,5]
def freq(x, prob=True):
    
    if sparse.issparse(x):
        x = x.toarray().flatten()
    
    values = {}
    for value in x:
        if value in values:
            values[value] += 1
        else:
            values[value] = 1
    
    xi = np.array(list(values.keys()))
    ni = np.array(list(values.values()))
    
    if prob:
        ni = ni / ni.sum()
    
    return xi, ni

print(freq(x, True))
print(freq(x, False))

(array([8, 3, 2, 1, 4, 5, 6]), array([0.11764706, 0.23529412, 0.29411765, 0.11764706, 0.05882353,
       0.11764706, 0.05882353]))
(array([8, 3, 2, 1, 4, 5, 6]), array([2, 4, 5, 2, 1, 2, 1]))


Zad 2

In [3]:
y = ['a', 'b', 'c', 'd', 'e', 'a', 'b', 'c', 'd', 'e']
x = [10, 20, 30, 40, 50, 10, 20, 30, 60, 90]

def freq2(x, y, prob=True):
    
    if sparse.issparse(x):
        x = x.toarray().flatten()
        
    if sparse.issparse(y):
        y = y.toarray().flatten()
    
    pairs = list(zip(x, y))
    unique_pairs, counts = np.unique(pairs, axis=0, return_counts=True)
    
    xi = np.unique(x)
    yi = np.unique(y)
    
    if prob:
        counts = counts / np.sum(counts)
    
    return xi, yi, counts

print(freq2(x, y, True))
print(freq2(x, y, False))

(array([10, 20, 30, 40, 50, 60, 90]), array(['a', 'b', 'c', 'd', 'e'], dtype='<U1'), array([0.2, 0.2, 0.2, 0.1, 0.1, 0.1, 0.1]))
(array([10, 20, 30, 40, 50, 60, 90]), array(['a', 'b', 'c', 'd', 'e'], dtype='<U1'), array([2, 2, 2, 1, 1, 1, 1]))


Zad 3

In [4]:
x = [1, 5, 8, 5, 2]
y = ['a', 'a', 'a', 'b', 'b']

def entropy(x):
    values, probabilities = freq(x, prob=True)
    return -np.sum(probabilities * np.log2(probabilities))

def infogain(x, y):
    h_x = entropy(x)
    h_y = entropy(y)
    
    x_vals, y_vals, joint_probs = freq2(x, y, prob=True)
    h_xy = -np.sum(joint_probs * np.log2(joint_probs + 1e-10))
    
    return h_x + h_y - h_xy

print(f"H(X): {entropy(x)}")
print(f"H(Y): {infogain(x, y)}")

H(X): 1.9219280948873623
H(Y): 0.5709505951760163


Zad 4

In [5]:
plik = pd.read_csv("zoo.csv")
x = plik["type"]
plik = plik.drop(columns=["type", "animal"])
dane = []
for i in plik:
    y = plik[i]
    dane.append([i, entropy(y), infogain(x, y)])
    
df = pd.DataFrame(dane, columns=["columns", "entropy", "infogain"])
df = df.sort_values(by="infogain", ascending=False)

print(df)

dane2 = []

for i in range(0, plik.shape[1] - 1):
    for j in range (i+1, plik.shape[1]):
        dane2.append([plik.columns[i], plik.columns[j], infogain(plik[plik.columns[i]], plik[plik.columns[j]])])

df = pd.DataFrame(dane2, columns=["columns1", "columns2", "infogain"])
df = df.sort_values(by="infogain", ascending=False)

print(df)

     columns   entropy  infogain
12      legs  2.033811  1.363047
3       milk  0.974320  0.974320
7    toothed  0.968587  0.865694
2       eggs  0.979466  0.830138
0       hair  0.984030  0.790675
1   feathers  0.717950  0.717950
8   backbone  0.676163  0.676163
9   breathes  0.737490  0.614494
13      tail  0.822837  0.500460
4   airborne  0.791066  0.469703
11      fins  0.653840  0.466614
5    aquatic  0.939685  0.389487
15   catsize  0.988016  0.308490
10  venomous  0.399382  0.133090
6   predator  0.991427  0.093447
14  domestic  0.553898  0.050669
     columns1  columns2  infogain
29       eggs      milk  0.787060
2        hair      milk  0.659966
1        hair      eggs  0.550778
25   feathers      legs  0.497238
95   backbone      legs  0.458314
..        ...       ...       ...
81   predator      tail  0.000259
32       eggs  predator  0.000097
62   airborne      tail  0.000065
59   airborne  venomous  0.000052
108  venomous  domestic  0.000008

[120 rows x 3 columns]


Zad 5 pododawane w zad 1 i 2